version: 2
jobs:
  build:
    machine:
      image: circleci/classic:latest
    steps:
      - checkout
      - run: sudo rm -f /var/lib/dpkg/lock
      - run: sudo apt-get update
      - run: sudo apt-get install -y genisoimage
      - run: cp -r config_template config/
      - run: sudo bash generate_iso.sh
      - run: ls -la
